# Generated by Django 3.2.12 on 2022-04-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.TextField(blank=True, null=True)),
                ('battery', models.IntegerField(default=100)),
            ],
        ),
    ]
